from lower_ir import (
    MPKProgram,
    BufferAlloc,
    WarpRegion,
    OpCall,
    Sync,
)


def emit_buffer(buf: BufferAlloc) -> str:
    if buf.scope == "shared":
        return (
            f"// buffer {buf.name}\n"
            f"// stages = {buf.stages}\n"
            f"// allocate {buf.name}[{buf.stages}] in shared memory"
        )

    return (
        f"// buffer {buf.name}, "
        f"scope={buf.scope}, stages={buf.stages}"
    )


def emit_op(op: OpCall, indent: int = 4) -> str:
    pad = " " * indent

    # Generic stub. moe_linear uses moe_linear_codegen.emit_moe_linear.
    if op.op == "tma_K":
        return f"{pad}tma_K_impl();"

    if op.op == "tma_V":
        return f"{pad}tma_V_impl();"

    if op.op == "mma_QK":
        return f"{pad}mma_QK_impl();"

    if op.op == "soft":
        return f"{pad}softmax_impl();"

    if op.op == "mma_PV":
        return f"{pad}mma_PV_impl();"

    return f"{pad}{op.op}_impl();"


def emit_warp_region(region: WarpRegion) -> str:
    lines = []

    lines.append(
        f"if (warp_id() == {region.warp}) {{"
    )

    for stmt in region.body:
        if isinstance(stmt, OpCall):
            lines.append(
                emit_op(stmt, indent=4)
            )

    lines.append("}")

    return "\n".join(lines)


def emit_sync(sync: Sync) -> str:
    return (
        f"// sync {sync.pipeline}: "
        f"warp {sync.producer_warp} -> "
        f"warp {sync.consumer_warp}"
    )


def emit_cuda(program: MPKProgram) -> str:
    lines = []

    lines.append("// Generated by Twill Translator")
    lines.append("")

    lines.append("// ---- Buffers ----")
    for buf in program.buffers:
        lines.append(emit_buffer(buf))
        lines.append("")

    lines.append("// ---- Warp-specialized ops ----")
    for region in program.warp_regions:
        lines.append(emit_warp_region(region))
        lines.append("")

    lines.append("// ---- Synchronization ----")
    for sync in program.syncs:
        lines.append(emit_sync(sync))

    return "\n".join(lines)